// lib/pages/languages.dart
//
// Table centrale de toutes les chaînes traduisibles de l'application.
// Convention de clés : namespace_sousCle (ex: sidebar_home, profile_logout)
// pour éviter les collisions entre pages qui utilisent des mots similaires.

const Map<String, Map<String, String>> languages = {
  'fr': {
    // ── Login (déjà existant) ──
    'welcome back': 'content de vous voir',
    'subtitle': 'Connectez-vous pour voir les conseils du jour pour vos champs',
    'appSubtitle': 'Connaissez votre terre, \n cultivez avec confiance',
    'forgotPassword': 'Mot de passe oublié ?',
    'needHelp': 'Besoin d aide ? Contactez votre bureau de vulgarisation local',
    'login': 'Connexion',
    'email': 'Adresse e-mail',
    'password': 'Mot de passe',
    'welcome': 'Bienvenue',

    // ── Sidebar / Navigation (titres + drawer + bottom nav) ──
    'nav_home': 'Accueil',
    'nav_newObservation': 'Nouvelle Observation',
    'nav_newObservation_short': 'Observer',
    'nav_result': 'Résultat',
    'nav_history': 'Historique',
    'nav_profile': 'Profil',
    'drawer_menu': 'Menu',
    'drawer_logout': 'Déconnexion',

    // ── Profil ──
    'profile_changePhoto': 'Changer la photo',
    'profile_defaultName': 'Nom Utilisateur',
    'profile_defaultEmail': 'utilisateur@email.com',
    'profile_phone': 'Téléphone',
    'profile_phoneValue': '+216 00 000 000',
    'profile_location': 'Localisation',
    'profile_locationValue': 'Tunis, Tunisie',
    'profile_editProfile': 'Modifier le profil',
    'profile_changePassword': 'Changer le mot de passe',
    'profile_language': 'Langue',
    'profile_about': 'À propos de Bassiana',
    'profile_logout': 'Déconnexion',

    // ── Historique ──
    'history_filterAllPlots': 'Toutes les parcelles',
    'history_filterLast30Days': '30 derniers jours',
    'history_month_august2026': 'Août 2026',
    'history_month_july2026': 'Juillet 2026',
    'history_plotA': 'Parcelle A – Oliveraie',
    'history_plotB': 'Parcelle B – Champ de blé',
    'history_plotC': 'Parcelle C – Agrumes',
    'history_badge_irrigateNow': 'Irriguer maintenant',
    'history_badge_goodConditions': 'Bonnes conditions',
    'history_badge_sowNow': 'Semer maintenant',

    // ── Home / En-tête ──
    'home_greeting_morning': 'Bonjour',
    'home_greeting_afternoon': 'Bon après-midi',
    'home_greeting_evening': 'Bonsoir',
    'home_location': 'Tunis, Tunisie',
    'home_todaysWeather': 'Météo du jour',
    'home_weatherUnavailable': 'Météo indisponible',
    'home_advice_title': "Conseil du jour",
    'home_advice_headline': "Il est temps d'irriguer",
    'home_advice_body': "L'humidité du sol est faible, aucune pluie prévue durant les trois prochains jours.",
    'home_advice_seeFullAnalysis': "Voir l'analyse complète",
    'home_newObservation_title': 'Nouvelle Observation',
    'home_newObservation_subtitle': "Enregistrez les données du champ pour des conseils actualisés",
    'home_yourField_title': 'Votre champ',
    'home_yourField_plot': 'Parcelle A – Oliveraie',
    'home_yourField_lastChecked': 'Dernière vérification il y a 2 jours',
    'home_yourField_moistureLow': 'Humidité – Faible',

    // ── Jours de la semaine / mois (pour la date formatée) ──
    'day_monday': 'Lundi', 'day_tuesday': 'Mardi', 'day_wednesday': 'Mercredi',
    'day_thursday': 'Jeudi', 'day_friday': 'Vendredi', 'day_saturday': 'Samedi', 'day_sunday': 'Dimanche',
    'month_january': 'Janvier', 'month_february': 'Février', 'month_march': 'Mars',
    'month_april': 'Avril', 'month_may': 'Mai', 'month_june': 'Juin',
    'month_july': 'Juillet', 'month_august': 'Août', 'month_september': 'Septembre',
    'month_october': 'Octobre', 'month_november': 'Novembre', 'month_december': 'Décembre',

    // ── Nouvelle Observation ──
    'newObs_whichPlot': 'Quelle parcelle ?',
    'newObs_plotA': 'Parcelle A – Olive',
    'newObs_plotB': 'Parcelle B – Blé',
    'newObs_plotC': 'Parcelle C – Agrumes',
    'newObs_cropType': 'Type de culture',
    'newObs_crop_olive': 'Olive',
    'newObs_crop_wheat': 'Blé',
    'newObs_crop_citrus': 'Agrumes',
    'newObs_crop_tomato': 'Tomate',
    'newObs_soilMoisture': 'Humidité du sol',
    'newObs_moisture_low': 'Faible',
    'newObs_moisture_medium': 'Moyenne',
    'newObs_moisture_high': 'Élevée',
    'newObs_dry': 'Sec',
    'newObs_wet': 'Humide',
    'newObs_soilType': 'Type de sol',
    'newObs_soil_sandy': 'Sableux',
    'newObs_soil_loamy': 'Limoneux',
    'newObs_soil_clay': 'Argileux',
    'newObs_fieldSize': 'Taille du champ (ha)',
    'newObs_addPhoto': 'Ajouter une photo',
    'newObs_optional': '(optionnel)',
    'newObs_tapToAddPhoto': 'Touchez pour prendre ou importer une photo',
    'newObs_notes': 'Notes',
    'newObs_notesHint': 'Autre chose à mentionner ?',
    'newObs_analyzeButton': "Analyser et obtenir des conseils",

    // ── Résultat ──
    'result_header': 'Parcelle A — Oliveraie · Aujourd\'hui',
    'result_needsAttention': 'ATTENTION REQUISE',
    'result_irrigateNow': 'Irriguer maintenant',
    'result_bestTime': "Meilleur moment : dans les 24 prochaines heures",
    'result_soilMoisture': 'Humidité du sol',
    'result_soilMoistureValue': '32 % · Faible',
    'result_soilQuality': 'Qualité du sol',
    'result_soilQualityValue': 'Sableux, drainage rapide',
    'result_weatherAhead': 'Météo à venir',
    'result_weatherAheadValue': 'Sec, 31°C en moyenne',
    'result_whyMatters_title': 'Pourquoi c\'est important',
    'result_whyMatters_body': "Votre sol s'assèche plus vite que la normale pour un terrain sableux, et les prochains jours restent chauds et secs. Irriguer maintenant protégera le développement des racines avant l'apparition du stress.",
    'result_whatToDo_title': 'Que faire',
    'result_step1': 'Irriguer dans les 24 prochaines heures',
    'result_step2': 'Arroser légèrement et fréquemment — le sol sableux draine vite',
    'result_step3': "Revérifier l'humidité du sol dans 3 jours",
    'result_saveToHistory': "Enregistrer dans l'historique",
    'result_newObservation': 'Nouvelle Observation',
  },

  'en': {
    'welcome back': 'welcome back',
    'subtitle': "Log in to see today's advice for your fields",
    'appSubtitle': 'Know your land,\n grow with confidence',
    'forgotPassword': 'Forgot password?',
    'needHelp': 'Need help? Contact your local extension office',
    'login': 'Login',
    'email': 'Email address',
    'password': 'Password',
    'welcome': 'Welcome',

    'nav_home': 'Home',
    'nav_newObservation': 'New Observation',
    'nav_newObservation_short': 'Observe',
    'nav_result': 'Result',
    'nav_history': 'History',
    'nav_profile': 'Profile',
    'drawer_menu': 'Menu',
    'drawer_logout': 'Logout',

    'profile_changePhoto': 'Change photo',
    'profile_defaultName': 'User Name',
    'profile_defaultEmail': 'user@email.com',
    'profile_phone': 'Phone',
    'profile_phoneValue': '+216 00 000 000',
    'profile_location': 'Location',
    'profile_locationValue': 'Tunis, Tunisia',
    'profile_editProfile': 'Edit profile',
    'profile_changePassword': 'Change password',
    'profile_language': 'Language',
    'profile_about': 'About Bassiana',
    'profile_logout': 'Logout',

    'history_filterAllPlots': 'All plots',
    'history_filterLast30Days': 'Last 30 days',
    'history_month_august2026': 'August 2026',
    'history_month_july2026': 'July 2026',
    'history_plotA': 'Plot A – Olive Grove',
    'history_plotB': 'Plot B – Wheat Field',
    'history_plotC': 'Plot C – Citrus',
    'history_badge_irrigateNow': 'Irrigate Now',
    'history_badge_goodConditions': 'Good Conditions',
    'history_badge_sowNow': 'Sow Now',

    'home_greeting_morning': 'Good morning',
    'home_greeting_afternoon': 'Good afternoon',
    'home_greeting_evening': 'Good evening',
    'home_location': 'Tunis, Tunisia',
    'home_todaysWeather': "Today's Weather",
    'home_weatherUnavailable': 'Weather unavailable',
    'home_advice_title': "Today's Advice",
    'home_advice_headline': 'Time to Irrigate',
    'home_advice_body': 'Soil moisture is low, no rain expected for the next three days.',
    'home_advice_seeFullAnalysis': 'See full analysis',
    'home_newObservation_title': 'New Observation',
    'home_newObservation_subtitle': "Log today's field data for fresh advice",
    'home_yourField_title': 'Your Field',
    'home_yourField_plot': 'Plot A – Olive Grove',
    'home_yourField_lastChecked': 'Last checked 2 days ago',
    'home_yourField_moistureLow': 'Moisture – Low',

    'day_monday': 'Monday', 'day_tuesday': 'Tuesday', 'day_wednesday': 'Wednesday',
    'day_thursday': 'Thursday', 'day_friday': 'Friday', 'day_saturday': 'Saturday', 'day_sunday': 'Sunday',
    'month_january': 'January', 'month_february': 'February', 'month_march': 'March',
    'month_april': 'April', 'month_may': 'May', 'month_june': 'June',
    'month_july': 'July', 'month_august': 'August', 'month_september': 'September',
    'month_october': 'October', 'month_november': 'November', 'month_december': 'December',

    'newObs_whichPlot': 'Which plot?',
    'newObs_plotA': 'Plot A – Olive',
    'newObs_plotB': 'Plot B – Wheat',
    'newObs_plotC': 'Plot C – Citrus',
    'newObs_cropType': 'Crop Type',
    'newObs_crop_olive': 'Olive',
    'newObs_crop_wheat': 'Wheat',
    'newObs_crop_citrus': 'Citrus',
    'newObs_crop_tomato': 'Tomato',
    'newObs_soilMoisture': 'Soil moisture',
    'newObs_moisture_low': 'Low',
    'newObs_moisture_medium': 'Medium',
    'newObs_moisture_high': 'High',
    'newObs_dry': 'Dry',
    'newObs_wet': 'Wet',
    'newObs_soilType': 'Soil type',
    'newObs_soil_sandy': 'Sandy',
    'newObs_soil_loamy': 'Loamy',
    'newObs_soil_clay': 'Clay',
    'newObs_fieldSize': 'Field size (ha)',
    'newObs_addPhoto': 'Add a photo',
    'newObs_optional': '(optional)',
    'newObs_tapToAddPhoto': 'Tap to take or upload a photo',
    'newObs_notes': 'Notes',
    'newObs_notesHint': 'Anything else to mention?',
    'newObs_analyzeButton': 'Analyze & Get Advice',

    'result_header': 'Plot A — Olive Grove · Today',
    'result_needsAttention': 'NEEDS ATTENTION',
    'result_irrigateNow': 'Irrigate Now',
    'result_bestTime': 'Best time: within the next 24 hours',
    'result_soilMoisture': 'Soil Moisture',
    'result_soilMoistureValue': '32% · Low',
    'result_soilQuality': 'Soil Quality',
    'result_soilQualityValue': 'Sandy, fast-draining',
    'result_weatherAhead': 'Weather Ahead',
    'result_weatherAheadValue': 'Dry, 31°C avg',
    'result_whyMatters_title': 'Why this matters',
    'result_whyMatters_body': 'Your soil is drying faster than usual for sandy ground, and the coming days stay hot and dry. Irrigating now will protect root development before stress sets in.',
    'result_whatToDo_title': 'What to do',
    'result_step1': 'Irrigate within the next 24 hours',
    'result_step2': 'Use light, frequent watering — sandy soil drains fast',
    'result_step3': 'Recheck soil moisture in 3 days',
    'result_saveToHistory': 'Save to History',
    'result_newObservation': 'New Observation',
  },

  'ar': {
    'welcome back': 'مرحبا',
    'appSubtitle': 'اعرف أرضك،\nازرع بثقة',
    'forgotPassword': 'نسيت كلمة المرور؟',
    'needHelp': 'تحتاج مساعدة؟ اتصل بمكتب الإرشاد المحلي',
    'subtitle': 'سجل الدخول لرؤية نصائح اليوم لحقولك',
    'login': 'تسجيل الدخول',
    'email': 'البريد الإلكتروني',
    'password': 'كلمة المرور',
    'welcome': 'مرحبا بك',

    'nav_home': 'الرئيسية',
    'nav_newObservation': 'ملاحظة جديدة',
    'nav_newObservation_short': 'ملاحظة',
    'nav_result': 'النتيجة',
    'nav_history': 'السجل',
    'nav_profile': 'الملف الشخصي',
    'drawer_menu': 'القائمة',
    'drawer_logout': 'تسجيل الخروج',

    'profile_changePhoto': 'تغيير الصورة',
    'profile_defaultName': 'اسم المستخدم',
    'profile_defaultEmail': 'user@email.com',
    'profile_phone': 'الهاتف',
    'profile_phoneValue': '+216 00 000 000',
    'profile_location': 'الموقع',
    'profile_locationValue': 'تونس، تونس',
    'profile_editProfile': 'تعديل الملف الشخصي',
    'profile_changePassword': 'تغيير كلمة المرور',
    'profile_language': 'اللغة',
    'profile_about': 'حول Bassiana',
    'profile_logout': 'تسجيل الخروج',

    'history_filterAllPlots': 'كل القطع',
    'history_filterLast30Days': 'آخر 30 يومًا',
    'history_month_august2026': 'أوت 2026',
    'history_month_july2026': 'جويلية 2026',
    'history_plotA': 'القطعة أ – بستان الزيتون',
    'history_plotB': 'القطعة ب – حقل القمح',
    'history_plotC': 'القطعة ج – الحمضيات',
    'history_badge_irrigateNow': 'اسقِ الآن',
    'history_badge_goodConditions': 'ظروف جيدة',
    'history_badge_sowNow': 'ازرع الآن',

    'home_greeting_morning': 'صباح الخير',
    'home_greeting_afternoon': 'مساء الخير',
    'home_greeting_evening': 'مساء الخير',
    'home_location': 'تونس، تونس',
    'home_todaysWeather': 'طقس اليوم',
    'home_weatherUnavailable': 'الطقس غير متوفر',
    'home_advice_title': 'نصيحة اليوم',
    'home_advice_headline': 'حان وقت السقي',
    'home_advice_body': 'رطوبة التربة منخفضة، لا يتوقع سقوط أمطار خلال الأيام الثلاثة القادمة.',
    'home_advice_seeFullAnalysis': 'مشاهدة التحليل الكامل',
    'home_newObservation_title': 'ملاحظة جديدة',
    'home_newObservation_subtitle': 'سجّل بيانات الحقل اليوم للحصول على نصائح محدثة',
    'home_yourField_title': 'حقلك',
    'home_yourField_plot': 'القطعة أ – بستان الزيتون',
    'home_yourField_lastChecked': 'آخر فحص قبل يومين',
    'home_yourField_moistureLow': 'الرطوبة – منخفضة',

    'day_monday': 'الإثنين', 'day_tuesday': 'الثلاثاء', 'day_wednesday': 'الأربعاء',
    'day_thursday': 'الخميس', 'day_friday': 'الجمعة', 'day_saturday': 'السبت', 'day_sunday': 'الأحد',
    'month_january': 'جانفي', 'month_february': 'فيفري', 'month_march': 'مارس',
    'month_april': 'أفريل', 'month_may': 'ماي', 'month_june': 'جوان',
    'month_july': 'جويلية', 'month_august': 'أوت', 'month_september': 'سبتمبر',
    'month_october': 'أكتوبر', 'month_november': 'نوفمبر', 'month_december': 'ديسمبر',

    'newObs_whichPlot': 'أي قطعة؟',
    'newObs_plotA': 'القطعة أ – زيتون',
    'newObs_plotB': 'القطعة ب – قمح',
    'newObs_plotC': 'القطعة ج – حمضيات',
    'newObs_cropType': 'نوع المحصول',
    'newObs_crop_olive': 'زيتون',
    'newObs_crop_wheat': 'قمح',
    'newObs_crop_citrus': 'حمضيات',
    'newObs_crop_tomato': 'طماطم',
    'newObs_soilMoisture': 'رطوبة التربة',
    'newObs_moisture_low': 'منخفضة',
    'newObs_moisture_medium': 'متوسطة',
    'newObs_moisture_high': 'مرتفعة',
    'newObs_dry': 'جافة',
    'newObs_wet': 'رطبة',
    'newObs_soilType': 'نوع التربة',
    'newObs_soil_sandy': 'رملية',
    'newObs_soil_loamy': 'طينية طميية',
    'newObs_soil_clay': 'طينية',
    'newObs_fieldSize': 'مساحة الحقل (هكتار)',
    'newObs_addPhoto': 'إضافة صورة',
    'newObs_optional': '(اختياري)',
    'newObs_tapToAddPhoto': 'اضغط لالتقاط أو تحميل صورة',
    'newObs_notes': 'ملاحظات',
    'newObs_notesHint': 'أي شيء آخر تود ذكره؟',
    'newObs_analyzeButton': 'حلّل واحصل على نصائح',

    'result_header': 'القطعة أ — بستان الزيتون · اليوم',
    'result_needsAttention': 'يتطلب اهتمامًا',
    'result_irrigateNow': 'اسقِ الآن',
    'result_bestTime': 'أفضل وقت: خلال الـ 24 ساعة القادمة',
    'result_soilMoisture': 'رطوبة التربة',
    'result_soilMoistureValue': '32٪ · منخفضة',
    'result_soilQuality': 'جودة التربة',
    'result_soilQualityValue': 'رملية، سريعة التصريف',
    'result_weatherAhead': 'الطقس القادم',
    'result_weatherAheadValue': 'جاف، بمعدل 31 درجة مئوية',
    'result_whyMatters_title': 'لماذا هذا مهم',
    'result_whyMatters_body': 'تجف تربتك أسرع من المعتاد بالنسبة لأرض رملية، والأيام القادمة ستبقى حارة وجافة. سقي الحقل الآن سيحمي نمو الجذور قبل ظهور الإجهاد.',
    'result_whatToDo_title': 'ماذا تفعل',
    'result_step1': 'اسقِ خلال الـ 24 ساعة القادمة',
    'result_step2': 'استخدم سقيًا خفيفًا ومتكررًا — التربة الرملية تصرّف الماء بسرعة',
    'result_step3': 'أعد فحص رطوبة التربة بعد 3 أيام',
    'result_saveToHistory': 'حفظ في السجل',
    'result_newObservation': 'ملاحظة جديدة',
  },
};